pipeline:
  name: Windows Web Application yqzzo - deploy
  identifier: Windows_Web_Application_yqzzo_deploy
  orgIdentifier: my_org
  projectIdentifier: my_project
  tags:
    criticality: critical
    regulated: 'false'
  stages:
  - stage:
      name: Windows_Service
      identifier: Windows_Service
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Service
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Service"'
  - stage:
      name: Windows_Web-Content
      identifier: Windows_Web_Content
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Web_Content
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Web-Content"'
  - stage:
      name: MSI_Deploy
      identifier: MSI_Deploy
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: MSI_Deploy
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      MSI_Deploy"'
  - stage:
      name: IIS_MS_Web_Deploy
      identifier: IIS_MS_Web_Deploy
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: IIS_MS_Web_Deploy
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      IIS_MS_Web_Deploy"'
  - stage:
      name: Windows_Config_Deploy
      identifier: Windows_Config_Deploy
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Config_Deploy
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Config_Deploy"'
